# Python 실습 IV: Vectors, matrices and multidimensional arrays, 

In [2]:
import numpy as np

In [3]:
x=[[1,2],[3,4]]
x

[[1, 2], [3, 4]]

## Reshaping and resizing

In [4]:
data = np.array([[1, 2], [3, 4]])

In [11]:
# : 그 이후 모두 가지고 오너라, 슬라이싱
data[1:] 

array([[3, 4]])

In [12]:
data.reshape(4)
# 4개의 array로 만들어진 벡터로 만들어 줘!

array([1, 2, 3, 4])

In [13]:
y=np.arange(0,6,1)
y
# 시작값, 마지막은 끝값, 가운데 1은 디폴트

array([0, 1, 2, 3, 4, 5])

In [14]:
y.reshape([3,2])
# 3,2로 변환했다.

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
z=y.reshape([3,2])
z

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
z=z.flatten()
z
# 다시 펼쳐줌

array([0, 1, 2, 3, 4, 5])

In [17]:
z.shape

(6,)

In [18]:
z=z[:,np.newaxis]
z
# 새로운 축을 만든다, 차원이 증가함

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [19]:
z.shape

(6, 1)

## python numpy array reshaping

In [20]:
x=np.array([0,1,2,3,4])
x

array([0, 1, 2, 3, 4])

In [21]:
y=np.stack((x,x,x), axis=0)
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [22]:
y.shape

(3, 5)

In [23]:
y=np.stack((x,x,x), axis=1)
y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [24]:
y.shape

(5, 3)

## Broad casting

In [25]:
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [26]:
y=np.stack((x,x*2,x*3),axis=1)
y

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15]])

In [27]:
y.shape

(5, 3)

In [28]:
x.shape

(5,)

In [32]:
y/x
# shape 주의해주기

ValueError: operands could not be broadcast together with shapes (5,3) (5,) 

In [33]:
x1=np.array([1,2,3])
x1.shape

(3,)

In [34]:
y/x1
# 1차원 은 가로축이 맞아야 한다.

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.]])

In [35]:
z=x[:,np.newaxis]
z

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [36]:
z.shape

(5, 1)

In [37]:
y /z

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

## Concatenating

In [38]:
z =np.array([[1,2],[3,4]])
z

array([[1, 2],
       [3, 4]])

In [39]:
np.concatenate([z,z],axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [40]:
np.concatenate([z,z],axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

## Matrix Operation

In [41]:
np.array([[1,2],[3,4]]).shape

(2, 2)

In [42]:
np.linalg.det([[1,2],[3,4]])


-2.0000000000000004

In [43]:
np.round(np.linalg.det([[1,2],[3,4]]))
#round 쓰면 조금 더 깔끔하게 나타낼 수 있음

-2.0

In [44]:
np.linalg.matrix_rank([[1,2],[3,4]])
#[1,2],[3,4]-3*[1,2]
#([1,2]
#[0,-2])

2

In [45]:
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])
X, Y

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [46]:
X*Y
#성분곱

array([[ 5, 12],
       [21, 32]])

In [47]:
np.dot(X,Y)
#행렬곱

array([[19, 22],
       [43, 50]])

In [48]:
X@Y
#행렬곱

array([[19, 22],
       [43, 50]])